version: "3"
services:
  exporter:
    image: local/nutanix-exporter
    build: .
    command:
      #- "-log.level=DEBUG"
      - "-nutanix.conf=/config.yml"
    ports:
      - 9405:9405
    volumes:
      - ./config.yml:/config.yml
